version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: errors-sample
    volumes:
      - '.:/go/src/app'
    ports:
      - '9020:9020'
    tty: true
    stdin_open: true
